import { Entity, PrimaryGeneratedColumn, Column } from 'typeorm';

/**
 * Enumerates the application roles supported by the authentication system.
 */
export enum UserRole {
  USER = 'user',
  ADMIN = 'admin',
}

/**
 * Represents an authenticated platform user and the persisted credentials.
 */
@Entity('users')
export class User {
  /**
   * Primary identifier generated by the database.
   */
  @PrimaryGeneratedColumn()
  id!: number;

  /**
   * Unique e-mail address used for login and notifications.
   */
  @Column({ unique: true })
  email!: string;

  /**
   * Given name of the user.
   */
  @Column()
  name!: string;

  /**
   * Surname or family name of the user.
   */
  @Column()
  second_name!: string;

  /**
   * Hashed password stored for credential verification.
   */
  @Column()
  password!: string;

  /**
   * Signals whether the e-mail address has been confirmed.
   */
  @Column({ default: false })
  isVerified!: boolean;

  /**
   * Role granted to the user, driving authorization decisions.
   */
  @Column({
    type: 'enum',
    enum: UserRole,
    default: UserRole.USER,
  })
  role!: UserRole;
}
